---
version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  do-thing:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - path-filtering/set-parameters:
          base-revision: main
          output-path: /tmp/pipeline-params.json
          mapping: |
            sourcefile.txt source-changed true
      - continuation/continue:
          parameters: /tmp/pipeline-params.json
          configuration_path: .circleci/continue-config.yml

workflows:
  generate-config:
    jobs:
      - do-thing
