---
version: 2.1

parameters:
  source-changed:
    type: boolean
    default: false
  smoke-test-required:
    type: boolean
    default: false
  integration-test-required:
    type: boolean
    default: false
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  evil-workflow:
    jobs:
      - evil-job
  just-build:
    when:
      and:
        - not:
            equal: [main, << pipeline.git.branch >>]
        - << pipeline.parameters.source-changed >>
        - not: << pipeline.parameters.GHA_Action>>]
    jobs:
      - build
  build-test-integration-test-release:
    when:
      and:
        - equal: [main, << pipeline.git.branch >>]
        - << pipeline.parameters.source-changed >>
    jobs:
      - build
      - test
      - integration-test:
          requires:
            - test
      - release:
          requires:
            - integration-test

  smoke-test:
    when: << pipeline.parameters.smoke-test-required >>
    jobs:
      - smoke-test
      - pr-test-complete:
          requires:
            - smoke-test

  integration-test:
    when: << pipeline.parameters.integration-test-required >>
    jobs:
      - integration-test
      - pr-test-complete:
          requires:
            - integration-test

jobs:
  evil-job:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: "Evil job"
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: build
          command: echo "Doing a build"

  test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: test
          command: echo "Doing a unit test"

  smoke-test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: test
          command: echo "Doing a smoke test"

  integration-test:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: test
          command: echo "Doing a full integration test"

  pr-test-complete:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: echo "done"

  release:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: test
          command: echo "Doing a release"
